# version: "3"
# services:
#   react-app:
#     # stdin_open: true
#     # tty: true
#     build:
#       context: .
#     ports:
#       - "3005:3000"
#     volumes:
#       - ./src:/app/src
#     # environment:
#     #   - REACT_APP_NAME=akuu
#     #   - CHOKIDAR_USEPOLLING=true
#     env_file:
#       - ./.env


version: "3"
services:
  web-prod:
    # stdin_open: true
    # tty: true
    build:
      context: .
      # dockerfile: Dockerfile.prod
      args:
        - REACT_APP_NAME=akuudia
    ports:
      - "3004:80"
    # environment:
    #   - REACT_APP_NAME=akuu
    #   - CHOKIDAR_USEPOLLING=true
    # env_file:
    #   - ./.env
